[package]
name = "rust-dynamic-linker-error"
version = "0.0.0"
authors = ["Casey Rodarmor <casey@rodarmor.com>"]

[dependencies.openssl-sys]
git = "https://github.com/sfackler/rust-openssl"

[dependencies.core-graphics]
git = "https://github.com/servo/core-graphics-rs"

